gudo: false
language: ruby
cache: bundler
rvm:
- 2.6
branches:
  only:
  - jekyll
install:
- gem install bundler
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external
after_success:
- git clone https://$GH_REF
- cd $(basename ${GH_REF%.git})
- git config user.name "Travis-CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
- touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll Site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push -f "https://${DEPLOY_KEY}@${GH_REF}" ${TARGET_BRANCH} > /dev/null 2>&1
env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/PandasaurusR/PandasaurusR.github.io.git
  - TARGET_BRANCH: master
  - secure: mT5VRhCgKZ24A3pQAP4zYCys+z3pcL0dkdIQ7ZY7Az1BX/yELbhqlV2lEniabroP/I/3xZ8vu4EJCae3uDqxMe7iPLdcyVlIzFgcPUzt8I3v1TdcF/aOLo1TgrfB9b1WPX/Po7jILY2yBpF/p8gNDRQxW0VinUXPiM7Qt7Oh4XnPa37XzveCSd699+gsMxRT0IDAaywbK3o2qVXacQpab6Rz8a2ykdsMVReib0UQbT7PNuM9phd8Vuf7BqLgqpHBt97xGdvRofMl3pSFehe/eDd0N844BU0JFan2hKPftSHMV0UJj/I8qDjRhhEV/ZfDVyr9CIukDiUdU80GiOSBYvSSjtP4DnhOUbsUQ2Bjr1PFlM7SOVy48QQkggRqccqTlmFZyUmLfktAMlAYjlY8Jk0tA+TK50KVXmsnk6SBgSk8bo7zuXXpHwLXcD/m5t+2k7rnY8eXa8HLx4vtzo3XT82cItpjBAyYZuUJRp83knbHaE2aNuKYAzzIAtqYUoqXN/HxNFdrroRxamNba1/MPqvO3fmyC6mk4BmsWnKhdVMWsCxbdI/yRVgEjkFCUpJ7uOlE49+dJD9oDWQe84FZkXbQJUGCDHKDgMLP7Rd2dNjGe3RaeMnbUQjJPqQEKvDE0M88tsWhJNcoF74GvFdZeqMjeHw90x/HyNSwOSitKOo=
  - secure: Rvgl76YVoidOFwBcYPKgd+SEnydBdxRPRF4dbwwxN2mMCmAXqMJe+hNWK/5cjj91KJyD0Zb1DyDCfFCfJJqB2Buyr18ULShw2xZ0XlKTGzqWEedPt/0tM4E/OphicvubV5rGPxdSEP9/i0Libg9ctpVmHx7QpZYyUHZTLkrOnKR+8hkH4Pr1Xw7KzFLZ+ryyt40Qflb1HqrXfVXG2FejnBLTeVXrb/tCptNpp++rGRlp8mPfV+kyKLfrBnGyXZCAlPXis+FsYlDYNtfiYINlMJ9HuzeuACfSoTLUyY1jOiKcK0yE/vbssV77SGR8Cv627cyDxSK0ChRP3MmAnAKka6ktxLqtdyNgpcdCxH6RJg83qFNGOVzTbtqwBhrO8dDtPk3N4ychy9NPrBQfkksHW/iDQQdgcCbRe8GY4uM6HLZbZAjegQd4ydasfmXBKiDLRNhmiNpeSV9iTKfXfeH+UDfcAbmGOwvhVmMpDNm1DoRtU0O8OnXGGa653sYLSog30gkb6zBjczbcccMdWgwpVNVnxu9oDLZEWewgPudJ1yVjcoZ0KB72RfavjzBELvDJV+1k7CpCWda2Jk8LlHNTczgwpWeBwXveG2IkOplwNJZ15dQWMc5XcgBQP2Idk55zvDJSO4/+7CYZn2S0NLrQ95lgadut7saUpiJaoJDF3oM=
